### ISSUE TITLE
关于检查点的问问题

### ISSUE THREAD

**Issue by Oona97** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#10]
您好，我看到readme提示在迁移学习之前要先进行分类任务，以生成检查点
但我先运行python3 classification.py --datadir "./datasets" --max_epoch 100之后
再运行python3 DDC.py --datadir "./datasets" --backbone "CNN1D" --pretrained False --kernel "CORAL"
还是会报错[Errno 2] No such file or directory: './checkpoints/CNN1D_checkpoint.tar'

不知道是哪里有问题
小白打扰了，作者见谅~

**Comment by Xiaohan-Chen** [comment]
The default network of classification.py is 'ResNet', if you want to train DDC.py with CNN1D backbone, you need to run ```python3 classification.py --datadir "./datasets" --backbone 'CNN1D'```
