### ISSUE TITLE
关于CWRU数据集

### ISSUE THREAD

**Issue by yangling-bit** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#2]
在PreparData下的CWRU.py文件中，要求使用如下固定格式的mat文件，不知该文件是由官方CWRU数据集怎样转换来的，可否求一份转换源码，谢谢！！

dataset/
  └── CWRU/
      ├── Drive_end_0/
      │   └── 97.mat 109.mat 122.mat 135.mat 173.mat 189.mat 201.mat 213.mat 226.mat 238.mat
      ├── Drive_end_1/
      │   └── 98.mat 110.mat 123.mat 136.mat 175.mat 190.mat 202.mat 214.mat 227.mat  239.mat
      ├── Drive_end_2/
      │   └── 99.mat 111.mat 124.mat 137.mat 176.mat 191.mat 203.mat 215.mat 228.mat 240.mat
      └── Drive_end_3/
          └── 100.mat 112.mat 125.mat 138.mat 177.mat 192.mat 204.mat 217.mat 229.mat 241.mat

**Comment by Xiaohan-Chen** [comment]
你好，CWRU官方网站下载的数据即为`mat`格式，无需转换。
