### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by JoysonYou** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#3]
I tried to download the dataset from CWRU, but found the file named 173.mat was missing, could it be 174.mat?
dataset/
  └── CWRU/
      ├── Drive_end_0/
      │   └── 97.mat 109.mat 122.mat 135.mat 173.mat 189.mat 201.mat 213.mat 226.mat 238.mat

**Comment by Xiaohan-Chen** [comment]
Thanks for finding this typo! The correct file name should be "174.mat" rather than "173.mat" (0.014 inches inner race fault under load 0HP). We will update the "readme.md" file and 'PreparData/CWRU.py' file later.

**Comment by JoysonYou** [comment]
You are welcome. Also, I think the 'dataset' may be changed to 'datasets' as I got an error about the root when running the classification, it's just a small typo. After all, thanks for sharing your codes and I've learnt a lot from them.

**Comment by Xiaohan-Chen** [comment]
Thanks for reporting these problems, we have resolved the root and data name issues in this repository.
