### ISSUE TITLE
数据集中测试集没有用到

### ISSUE THREAD

**Issue by wuwangchuzhong12** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#6]
我看到您在程序里将数据划分为训练集、验证集和测试集，每次循环使用训练集训练模型，找到验证集准确率最高的轮次，并没有计算测试集的准确率？

**Comment by Xiaohan-Chen** [comment]
Yes, they are not used in the script, but it can be easily realized by calling the function `tester()` and replacing the parameter `dataloader`.

**Comment by wuwangchuzhong12** [comment]
好的    谢谢您的回答
