### ISSUE TITLE
对于OSDABP中的模型部分的一点问题

### ISSUE THREAD

**Issue by xu12345dd** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#7]
您好，我目前正在学习您的代码，主要运用了OSDABP这个模型，在这个模型中域对抗模块在哪里使用呢？如何实现开放集域适应的呢？

**Comment by Xiaohan-Chen** [comment]
您好，根据我的理解，作者并没有使用像DANN那样的对抗模块（如原论文图3所示），仅有一个Generator和Classifier。关于改模型如何识别open-set问题，可以阅读原文理解作者的思路。
