### ISSUE TITLE
about  article

### ISSUE THREAD

**Issue by zc198** [Xiaohan-Chen/transfer-learning-fault-diagnosis-pytorch#8]
请问本代码对应的论文名字是什么?刚接触深度学习，若方便请告知一下以便于小白学习，感谢

**Comment by Xiaohan-Chen** [comment]
你好，感谢对我们的项目感兴趣。该项目是我们发表在IEEE Transactions on Instrumentation and Measurement的一篇综述：[Deep Transfer Learning for Bearing Fault Diagnosis: A Systematic Review Since 2016](https://ieeexplore.ieee.org/document/10042467)，欢迎阅读与交流。
